#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

if [ -z "$CONFIG_ROOT" ]; then
    export CONFIG_ROOT=`dirname $(find $HOME -name .configroot -print -quit)`
fi 

# find the installers and run them iteratively
find $CONFIG_ROOT -path backups -prune -o -name install.sh -print | while read installer ; do sh -c "${installer}" ; done
